# Generated by Django 4.2.1 on 2023-06-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('currency_type', models.CharField(choices=[('local', 'Local Currency'), ('foreign', 'Foreign Currency')], max_length=10)),
                ('vendor_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.currency')),
            ],
        ),
    ]
