# Generated by Django 4.2.1 on 2023-06-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_businesspartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='item.currency'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='currency_type',
            field=models.CharField(choices=[('local', 'Local Currency'), ('foreign', 'Foreign Currency')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='vendor_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
