# Generated by Django 4.2.2 on 2023-06-14 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_stock_itemreceipt_itemdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.warehouse'),
        ),
        migrations.CreateModel(
            name='ItemReceiptinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docno', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.warehouse')),
            ],
        ),
    ]
