# Generated by Django 4.2.2 on 2023-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_warehouse_itemreceiptinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreceipt',
            name='docno',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
