# Generated by Django 4.2.2 on 2023-06-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_itemreceipt_docno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreceipt',
            name='docno',
        ),
        migrations.AddField(
            model_name='itemreceipt',
            name='item_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.itemreceiptinfo'),
        ),
    ]
