# Generated by Django 4.2.2 on 2023-06-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_remove_itemreceipt_docno_itemreceipt_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreceipt',
            name='item_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemreceiptinfo'),
        ),
    ]
