# Generated by Django 4.2.2 on 2023-06-16 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_businesspartner_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeliveryinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docno', models.PositiveIntegerField(default=1, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='itemdelivery',
            name='item_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemdeliveryinfo'),
        ),
    ]
